/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizador;

import Controlador.ControleInformacoes;
import Modelo.Jogador;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Yuri
 */
public class NovoJogo extends javax.swing.JFrame {
    
    private Jogador jogo;
    private ControleInformacoes tabela;
    private PainelJogadora tela;
    
    
    /**
     * Creates new form NovoJogo
     */
    public NovoJogo() {
        initComponents();
        this.jogo = new Jogador("Maria", 0, 0, 0, 0);
        this.tabela = new ControleInformacoes();
    }
    
    public NovoJogo(ControleInformacoes tabela, PainelJogadora telaPrincipal) {
        this.jogo = new Jogador("maria", 0, 0, 0, 0);
        this.tela = telaPrincipal;
        this.tabela = tabela;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resultadoJogo = new javax.swing.JTextField();
        salvarPontuacao = new javax.swing.JButton();
        cancelarPontuacao = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Novo Jogo");

        jLabel2.setText("Pontuação do Jogo:");

        resultadoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoJogoActionPerformed(evt);
            }
        });

        salvarPontuacao.setText("Salvar");
        salvarPontuacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarPontuacaoMouseClicked(evt);
            }
        });
        salvarPontuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarPontuacaoActionPerformed(evt);
            }
        });

        cancelarPontuacao.setText("Cancelar");
        cancelarPontuacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarPontuacaoMouseClicked(evt);
            }
        });
        cancelarPontuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarPontuacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoJogo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(salvarPontuacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarPontuacao)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(resultadoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarPontuacao)
                    .addComponent(cancelarPontuacao))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultadoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoJogoActionPerformed

    private void salvarPontuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarPontuacaoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_salvarPontuacaoActionPerformed

    private void cancelarPontuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarPontuacaoActionPerformed
        // TODO add your handling code here:
        jogo.setPlacar(-1);
    }//GEN-LAST:event_cancelarPontuacaoActionPerformed

    private void salvarPontuacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarPontuacaoMouseClicked
        // TODO add your handling code here:
        int placarJogo = Integer.parseInt(resultadoJogo.getText());
        if (placarJogo > 0 && placarJogo < 1000) {
            this.jogo.setPlacar(placarJogo);
            this.tabela.novoJogo(jogo);
            tela.atualizarTabela();
            this.dispose();
        } else {
                showMessageDialog(null, "Valor incorreto", "Error", ERROR_MESSAGE);
                }
    }//GEN-LAST:event_salvarPontuacaoMouseClicked

    private void cancelarPontuacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarPontuacaoMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarPontuacaoMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarPontuacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField resultadoJogo;
    private javax.swing.JButton salvarPontuacao;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
